name: packer manual run
run-name: Building AMI with Packer

on:
  workflow_dispatch:
    inputs:
      runInt:
        description: 'Run INT-packer (true/false)'
        required: true
        default: 'false'
      runProd:
        description: 'Run PROD-packer (true/false)'
        required: true
        default: 'false'

jobs:
  int-packer:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.runInt == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Job1
        run: echo "Running Job1"

  prod-packer:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.runProd == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Job2
        run: echo "Running Job2"
